### PR TITLE
Add some more common EAP install directories

### LINKED ISSUE #349: Research directories to include in "common directories" search
Need to do more research to find a good list of directories to check for.

Part of #335 .

### PR DESCRIPTION
**Pull request by noahl**
This covers EAP versions 6 and 7. (I researched EAP 5 too, but I don't have any known install directories for it.)

Closes #349 .

### CODE REVIEW

**Comment by chambridge** [comment]
@mdvickst You mentioned some additional common directories. Could you mention them here so we can add them to the default list.

**Comment by noahl** [comment]
@chambridge can we go ahead and merge this PR so we don't have it outstanding? We can always add more directories later.

**Review by chambridge — APPROVED** [review]
Yes, that's fine.

**Comment by mdvickst** [comment]
Here is quick list of install dirs that were reported by some customers. 

Most seem to be in /opt /usr or /app although I've also see /export and a few others. 

Maybe we could look in /opt /home /usr for any subdirs that have *jboss* in the name then scan those? And maybe look in / 1 or 2 levels deep for "jboss" dirs without following symlinks and xdev enabled?

/opt/jboss-eap-6.2_active;
/JBossEAP/jboss-eap-6.4;
/JBossAS/jboss-eap-6.2;
/opt/app/jboss/5.2.0-2/bin/run.jar;
/opt/hpom/share/jboss/5.1.0/bin/run.jar;
/opt/NA/server/ext/jboss/bin/run.jar;
/usr/local/jee/jboss-4.2.3.GA/bin/run.jar
/opt/deploy/jboss/jbossas6/jboss-modules.jar;   
/usr/share/java/jboss-modules.jar; /usr/share/jbossas/jboss-modules.jar;
/opt/app/jboss/4.3.0-6/bin/run.jar;
/opt/hpom/share/jboss/5.1.0/bin/run.jar;
/app/jboss
/app/jboss6

**Comment by noahl** [comment]
@mdvickst thanks for the list! I have a PR out right now to get the easy ones in your list, and I filed issues for the ones where we'll have to add more functionality to rho in order to check them.

**Pull request merged**
