### PR TITLE
Move man page to reStructured Text.

### LINKED ISSUE #301: Move man page to different format
After looking at our man page, the current format (troff?) seems unnecessarily difficult to actually write in. I suggest that we move to a different format and use pandoc (https://pandoc.org/) to convert to troff for the man page.

Another advantage would be that if we had the man page in a different format, it would be easier to convert to HTML for use in a hypothetical Sonar web interface.

I think Markdown and reStructuredText would be good formats, but there are plenty of options. I'm bringing this up now so that if we decide to go to a different format, Jamie won't have to suffer with troff.

@chambridge what do you think?

### PR DESCRIPTION
**Pull request by noahl**
This means that all of our documentation is in the same format, which
will enable us to share snippets between the man page and the other
docs in the future. It also makes the man page much easier to edit.

Closes #301 .

### CODE REVIEW

**Comment by noahl** [comment]
@jlprevatt you don't have to review this, but this is the change we were talking about. This lets us generate the rho man page from restructured text, which is the format the rest of the rho docs are in.

**Review by chambridge — COMMENTED** [review]
Looks fine, but we need to make adjustments to the rho.spec file so we can properly build the RPM on COPR.

Looks like we may need additional `BuildRequires` here that include *pandoc*:
https://github.com/quipucords/rho/blob/master/rho.spec#L16

And a step in the build phase that will generate the doc in the appropriate location:
https://github.com/quipucords/rho/blob/master/rho.spec#L37

**Comment by elyezer** [comment]
Sphinx has a man builder built in, have you tried using it?

Tomorrow I will pull this PR locally and try to run it.

**Comment by noahl** [comment]
@chambridge I pushed a new commit that does what you suggested. I looked at the copr documentation, but I don't see a way to test the COPR build locally. Is there a way to try it before we merge this PR?

**Comment by noahl** [comment]
@elyezer I have not tried the Sphinx man page builder. If it's okay with you, I do not want to make that change in this PR, because I want to get the format change done relatively quickly, and I don't think we gain a lot right now from using Sphinx specifically to generate our man page. In the long term, using Sphinx might make a lot of sense if we are generating the man page and a documentation site from the same source. Is that okay with you?

**Comment by elyezer** [comment]
@noahl sounds good

**Review by chambridge — APPROVED** [review]
LGTM!

**Pull request merged**
