### PR TITLE
Rename jboss.eap.running-versions to jboss.eap.running-paths

### LINKED ISSUE #397: Name of jboss.eap.running-versions fact is confusing
## Specify type:
- Bug
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
This fact is named `jboss.eap.running-versions` but it is actually the path to the directory where the jboss script is. While it is true that if you unpack the zip file and do not rename it, it usually includes the version of the jboss install in the name, the name of the directory is not a reliable "feature" to indicate the version of jboss.

___

### Version of rho:
[ 0.29 ]

### Expected behavior:
I would expect this to contain a numeric value, or to rename the fact to better match what it is actually reporting, the path to the jboss script.

### Actual behavior:
Provide the actual behavior for the program.

 jboss.eap.running-versions 
| -------------------------------------- |
 /path/to/top_dir_of_jboss 

### Steps to reproduce:
Scan a system with jboss running. Inspect the report.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora            | 25    | 3.6            | Bare Metal
Target System   | RHEL             | 7.4        | 2.7.5          | KVM

### PR DESCRIPTION
**Pull request by noahl**
Closes #397 .

### CODE REVIEW

**Review by chambridge — APPROVED** [review]
👍 . Can you regenerate the fact docs?

**Review by kdelee — APPROVED** [review]
LGTM, thanks!

**Review by elyezer — APPROVED** [review]
I will update automation jobs when this get merged.

**Comment by noahl** [comment]
@chambridge I regenerated the fact docs. You approved, so I'll go ahead and merge.

**Pull request merged**
